---
title: "First Knit"
author: "Your Name"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
I attended High School at University Preparatory. Yes, I did graduate in 2017.  
Both english and math are relatively easy, however this class is different. I have never programmed, so it's somewhat difficult.  
I did great in both subjects. However, I found that English is my strong suit.  

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
I am using a windows laptop.  
I would rate myself a 9, but this class is proving otherwise.  
My internet connection is great, with no issues. 
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
The name I prefer to be called is Leonel, by both my classmates and instructor.  
If I had to choose to be called something, I would choose to be called Leo.  
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
The thing I want to achieve in life is to retire my parents, and have financial freedom, all while helping people.    
The college subject I thoroughly enjoy is political science, hence why it's my major.     
The degree I am trying to achieve at Antelope Valley College is an associates in Political Science. However, I will be attending law school and hopefully simultaneously acquiring my masters, or doctorate.    
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
Yes, I have been to foreign countries. Specifically, Japan, Bahrain, and Australia, as well as an array of middle eastern countries I cannot disclose.    
Yes, I have been in the military, specifically the Marine Corps. Primarily stationed at MCAS Miaramar, and from there went TAD and on deployments.   
   
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
 






  




